name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # go to home directory
            cd ~

            # install git
            sudo apt update
            sudo apt install -y git

            # clone repo if not exists
            if [ ! -d "new_repo" ]; then
              git clone https://github.com/djashutosh673-hub/new_repo.git
            fi

            cd new_repo

            # pull latest code
            git pull origin main

            # install docker
            sudo apt install -y docker.io

            # stop old container
            docker stop myapp || true
            docker rm myapp || true

            # build image
            docker build -t myapp .

            # run container WITH DB CONNECTION
            docker run -d -p 80:80 --name myapp \
              -e DB_CONNECTION_STRING="Server=${{ secrets.RDS_HOST }};Database=${{ secrets.RDS_DB_NAME }};User=${{ secrets.RDS_USERNAME }};Password=${{ secrets.RDS_PASSWORD }}" \
              myapp